# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  php:
    image: php:8.2-apache
    container_name: php_container
    volumes:
      - ./src:/var/www/html
    environment:
      APACHE_SERVER_NAME: apache.local
    ports:
      - 8080:80
    command: >
      bash -c "docker-php-ext-install mysqli pdo pdo_mysql &&
               apache2-foreground"
    networks:
      - mysql_net
networks:
  mysql_net:

volumes:
  Db_data:
